version: 0.2

phases: 
    install:
        commands:
            - echo "installing something"
    pre_build:
        commands: 
            - echo "we are in the pre build phase"
    build:
        commands:
            - echo "we are in the build block"
            - echo "we will run some tests"
            - grep -R "<title>Next Gen SCADA Programmer Blog &#8211; Jacob Ramirez</title>\|<p class="site-description">Jacob Ramirez</p>" /*.html
    post_build:
        commands:
            - echo "we are in the post build phase"